name             'omnibus-chef-arm'
maintainer       'Ryan Hass'
maintainer_email 'ryan@invalidchecksum.net'
license          'Apache 2.0'
description      'Installs/Configures omnibus-chef-arm'
long_description 'Installs/Configures omnibus-chef-arm'
version          '0.1.0'

depends 'apt'
depends 'fancy_execute'
depends 'omnibus'
depends 'swap'
depends 'yum-epel'
depends 'git'
